# Sitio académico para el módulo Gestión de Bases de Datos

title: "Gestión de Bases de Datos"
description: "Recursos, apuntes y materiales del módulo GBD de ASIR"
baseurl: "" # el subpath de tu sitio, por ejemplo /blog
url: "https://adiezc10.github.io/GBD" # la URL base del sitio

# Información del autor
author:
  name: "Álvaro Diez Carrancio"
  email: "tu_email@ejemplo.com"
  github: "adiezc10"

# Tema
theme: jekyll-theme-slate # Puedes cambiarlo por otro como 'minimal', 'academicpages', etc.

# Navegación
show_downloads: true
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Configuración de colecciones (opcional)
collections:
  apuntes:
    output: true
  ejercicios:
    output: true
  proyectos:
    output: true

# Configuración de SEO
seo:
  name: "Gestión de Bases de Datos - ASIR"
  type: "Education"
  description: "Material académico para el módulo GBD impartido por Álvaro Diez"

# Exclude files from build
exclude:

