# Sitio académico para el módulo Gestión de Bases de Datos

title: "Gestión de Bases de Datos"
description: "Recursos, apuntes y materiales del módulo GBD de ASIR"
baseurl: "" # el subpath de tu sitio, por ejemplo /blog
url: "https://adiezc10.github.io/GBD" # la URL base del sitio

# Tema
theme: jekyll-theme-cayman

# Navegación
show_downloads: true
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true

# Configuración de colecciones (opcional)
collections:
  apuntes:
    output: true
  ejercicios:
    output: true
  proyectos:
    output: true

# Configuración de SEO
seo:
  name: "Gestión de Bases de Datos - ASIR"
  type: "Education"
  description: "Material académico para el módulo GBD"




